set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/

call vundle#begin()

Bundle 'gmarik/vundle'
Bundle 'tpope/vim-pathogen'
Bundle 'tpope/vim-rails'
Bundle 'tpope/vim-fugitive'
Bundle 'plasticboy/vim-markdown'
Bundle 'vim-scripts/TwitVim'
Bundle 'vim-scripts/gitignore.vim'
Bundle 'jamessan/vim-gnupg'
Bundle 'scrooloose/nerdtree'
Bundle 'xolox/vim-misc'
Bundle 'xolox/vim-session'
Bundle 'mattn/webapi-vim'
Bundle 'mattn/gist-vim'
Bundle 'Shougo/vimproc'
Bundle 'Shougo/vimshell'
Bundle 'scrooloose/syntastic'
Bundle 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}
Bundle '7kfpun/finance.vim'
Bundle 'ledger/vim-ledger'

" Autocomplete
Bundle 'ervandew/supertab'

" Snippets
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'

Bundle 'mediawiki'
Bundle 'muttrc.vim'
Bundle 'node.js'
Bundle 'itchyny/calendar.vim'
Bundle 'K0HAX/vim-pastebin'

call vundle#end()

execute pathogen#infect()

" Make sure the status line shows up all the time.
set laststatus=2

" I like syntax highlighting
syntax on

" Automatic indents
filetype plugin indent on
set smartindent
set background=dark
set autoread
set ruler
set switchbuf=useopen
set incsearch
set hlsearch

colorscheme torte
set backspace=indent,eol,start
set shiftwidth=4 tabstop=4 softtabstop=4
set expandtab

" Clear highlighting by pressing <CR> in command mode after a search
noremap <CR> :noh<CR><CR>
nnoremap <F12> "=strftime("%c")<CR>P
inoremap <F12> <C-R>=strftime("%c")<CR>
nnoremap <F5> :w<CR><CR>
inoremap <F5> <C-R>:w<CR><CR>
map     <C-n> :NERDTreeToggle<CR>
map     <C-h> :tabprevious<CR>
map     <C-l> :tabnext<CR>
"nnoremap <F6> :wq<CR><CR>
"inoremap <F6> <C-R>:wq<CR><CR>

" super sudo write
cno w!! w !sudo tee % >/dev/null
cnoremap daycal :Calendar -split=vertical -width=37 -day

" GPG Section
let g:GPGPreferArmor=1
let g:GPGPreferSign=1

augroup GnuPGExtra
    autocmd BufReadCmd,FileReadCmd *.\(gpg\|asc\|pgp\) call SetGPGOptions()
    " autocmd CursorHold *.\(gpg\|asc\|pgp\) quit
augroup END

function SetGPGOptions()
    set updatetime=60000
    set foldmethod=marker
    set foldclose=all
    set foldopen=insert
endfunction

"set autochdir
let NERDTreeChDirMode=2

:let g:session_autosave = 'no'
:let g:session_autoload = 'yes'
:let g:vim_markdown_folding_disabled = 1

:let g:calendar_google_calendar = 1
:let g:calendar_google_task = 1

" Begin TwitVim customizations.
nnoremap <F8> :FriendsTwitter<cr>
nnoremap <S-F8> :UserTwitter<cr>
nnoremap <A-F8> :RepliesTwitter<cr>
nnoremap <C-F8> :DMTwitter<cr>

" Begin finance.vim customization
let g:finance_watchlist = ['SQ']
"let g:finance_format' = '{symbol}: {LastTradePriceOnly ({Change})'
"let g:finance_separator' = '\n'

" Begin ledger.vim customization
let g:ledger_fold_blanks = 1

" make YCM compatible with UltiSnips (using supertab)
let g:ycm_key_list_select_completion = []
let g:ycm_key_list_previous_completion = []
let g:SuperTabDefaultCompletionType = '<C-n>'

" better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"

" Snippets customization
let g:UtiliSnipsExpandTrigger="<C-j>"
let g:UltiSnipsJumpForwardTrigger="<C-b>"
let g:UtiliSnipsJumpBackwardTrigger="<C-z>"

let maplocalleader = ',,'
