set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/

call vundle#begin()

Bundle 'gmarik/vundle'
Bundle 'tpope/vim-pathogen'
Bundle 'tpope/vim-rails'
Bundle 'tpope/vim-fugitive'
Bundle 'plasticboy/vim-markdown'
Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
Bundle 'vim-scripts/TwitVim'
Bundle 'vim-scripts/gitignore.vim'
Bundle 'jamessan/vim-gnupg'
Bundle 'scrooloose/nerdtree'
Bundle 'xolox/vim-misc'
Bundle 'xolox/vim-session'
Bundle 'mattn/webapi-vim'
Bundle 'mattn/gist-vim'
Bundle 'Shougo/vimproc'
Bundle 'Shougo/vimshell'
Bundle 'scrooloose/syntastic'
Bundle 'vim-scripts/mediawiki.vim'
Bundle 'daisuzu/facebook.vim'
Bundle 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}

Bundle 'git-diff'
Bundle 'mediawiki'
Bundle 'muttrc.vim'
Bundle 'node.js'
Bundle 'vim-diff'
Bundle 'itchyny/calendar.vim'

" Required for Facebook
Bundle 'facebook/fbconsole'
Bundle 'tyru/open-browser.vim'
" End required

call vundle#end()

execute pathogen#infect()

" Make sure the status line shows up all the time.
set laststatus=2

" I like syntax highlighting
syntax on

" Automatic indents
filetype plugin indent on
set smartindent
set background=dark
set autoread
set ruler
set switchbuf=useopen

colorscheme torte
set backspace=indent,eol,start
set shiftwidth=4 tabstop=4 softtabstop=4
set expandtab

" Clear highlighting by pressing <CR> in command mode after a search
noremap <CR> :noh<CR><CR>
nnoremap <F12> "=strftime("%c")<CR>P
inoremap <F12> <C-R>=strftime("%c")<CR>
nnoremap <F5> :w<CR><CR>
inoremap <F5> <C-R>:w<CR><CR>
map     <C-n> :NERDTreeToggle<CR>
map     <C-h> :tabprevious<CR>
map     <C-l> :tabnext<CR>
"nnoremap <F6> :wq<CR><CR>
"inoremap <F6> <C-R>:wq<CR><CR>

" super sudo write
cno w!! w !sudo tee % >/dev/null
cnoremap daycal :Calendar -split=vertical -width=37 -day

" GPG Section
let g:GPGPreferArmor=1
let g:GPGPreferSign=1

augroup GnuPGExtra
    autocmd BufReadCmd,FileReadCmd *.\(gpg\|asc\|pgp\) call SetGPGOptions()
    " autocmd CursorHold *.\(gpg\|asc\|pgp\) quit
augroup END

function SetGPGOptions()
    set updatetime=60000
    set foldmethod=marker
    set foldclose=all
    set foldopen=insert
endfunction

set autochdir
let NERDTreeChDirMode=2

:let g:session_autosave = 'no'
:let g:session_autoload = 'yes'
:let g:vim_markdown_folding_disabled = 1

:let g:calendar_google_calendar = 1
:let g:calendar_google_task = 1

" Begin TwitVim customizations.
nnoremap <F8> :FriendsTwitter<cr>
nnoremap <S-F8> :UserTwitter<cr>
nnoremap <A-F8> :RepliesTwitter<cr>
nnoremap <C-F8> :DMTwitter<cr>

